package com.uds.tc.common.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.8
 * 2016-05-06T14:08:22.564+08:00
 * Generated source version: 3.0.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IWebCommonService")
@XmlSeeAlso({ObjectFactory.class})
public interface IWebCommonService {

    @WebMethod(operationName = "CustomizeNonTcCommand2", action = "http://tempuri.org/IWebCommonService/CustomizeNonTcCommand2")
    @Action(input = "http://tempuri.org/IWebCommonService/CustomizeNonTcCommand2", output = "http://tempuri.org/IWebCommonService/CustomizeNonTcCommand2Response")
    @RequestWrapper(localName = "CustomizeNonTcCommand2", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.CustomizeNonTcCommand2")
    @ResponseWrapper(localName = "CustomizeNonTcCommand2Response", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.CustomizeNonTcCommand2Response")
    @WebResult(name = "CustomizeNonTcCommand2Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String customizeNonTcCommand2(
        @WebParam(name = "commandId", targetNamespace = "http://tempuri.org/")
        java.lang.String commandId,
        @WebParam(name = "command1", targetNamespace = "http://tempuri.org/")
        java.lang.Object command1,
        @WebParam(name = "command2", targetNamespace = "http://tempuri.org/")
        java.lang.Object command2,
        @WebParam(name = "command3", targetNamespace = "http://tempuri.org/")
        java.lang.Object command3
    );

    @WebMethod(operationName = "CustomizeNonTcCommand3", action = "http://tempuri.org/IWebCommonService/CustomizeNonTcCommand3")
    @Action(input = "http://tempuri.org/IWebCommonService/CustomizeNonTcCommand3", output = "http://tempuri.org/IWebCommonService/CustomizeNonTcCommand3Response")
    @RequestWrapper(localName = "CustomizeNonTcCommand3", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.CustomizeNonTcCommand3")
    @ResponseWrapper(localName = "CustomizeNonTcCommand3Response", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.CustomizeNonTcCommand3Response")
    @WebResult(name = "CustomizeNonTcCommand3Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String customizeNonTcCommand3(
        @WebParam(name = "commandId", targetNamespace = "http://tempuri.org/")
        java.lang.String commandId,
        @WebParam(name = "command1", targetNamespace = "http://tempuri.org/")
        byte[] command1,
        @WebParam(name = "command2", targetNamespace = "http://tempuri.org/")
        byte[] command2,
        @WebParam(name = "command3", targetNamespace = "http://tempuri.org/")
        byte[] command3
    );

    @WebMethod(operationName = "CustomizeCommand", action = "http://tempuri.org/IWebCommonService/CustomizeCommand")
    @Action(input = "http://tempuri.org/IWebCommonService/CustomizeCommand", output = "http://tempuri.org/IWebCommonService/CustomizeCommandResponse")
    @RequestWrapper(localName = "CustomizeCommand", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.CustomizeCommand")
    @ResponseWrapper(localName = "CustomizeCommandResponse", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.CustomizeCommandResponse")
    @WebResult(name = "CustomizeCommandResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String customizeCommand(
        @WebParam(name = "commandId", targetNamespace = "http://tempuri.org/")
        java.lang.String commandId,
        @WebParam(name = "command1", targetNamespace = "http://tempuri.org/")
        java.lang.String command1
    );

    @WebMethod(operationName = "SendSpecialCommand", action = "http://tempuri.org/IWebCommonService/SendSpecialCommand")
    @Action(input = "http://tempuri.org/IWebCommonService/SendSpecialCommand", output = "http://tempuri.org/IWebCommonService/SendSpecialCommandResponse")
    @RequestWrapper(localName = "SendSpecialCommand", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.SendSpecialCommand")
    @ResponseWrapper(localName = "SendSpecialCommandResponse", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.SendSpecialCommandResponse")
    @WebResult(name = "SendSpecialCommandResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSpecialCommand(
        @WebParam(name = "commandId", targetNamespace = "http://tempuri.org/")
        java.lang.String commandId,
        @WebParam(name = "command1", targetNamespace = "http://tempuri.org/")
        java.lang.String command1
    );

    @WebMethod(operationName = "CustomizeNonTcCommand", action = "http://tempuri.org/IWebCommonService/CustomizeNonTcCommand")
    @Action(input = "http://tempuri.org/IWebCommonService/CustomizeNonTcCommand", output = "http://tempuri.org/IWebCommonService/CustomizeNonTcCommandResponse")
    @RequestWrapper(localName = "CustomizeNonTcCommand", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.CustomizeNonTcCommand")
    @ResponseWrapper(localName = "CustomizeNonTcCommandResponse", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.CustomizeNonTcCommandResponse")
    @WebResult(name = "CustomizeNonTcCommandResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String customizeNonTcCommand(
        @WebParam(name = "commandId", targetNamespace = "http://tempuri.org/")
        java.lang.String commandId,
        @WebParam(name = "command1", targetNamespace = "http://tempuri.org/")
        java.lang.String command1,
        @WebParam(name = "command2", targetNamespace = "http://tempuri.org/")
        java.lang.String command2,
        @WebParam(name = "command3", targetNamespace = "http://tempuri.org/")
        java.lang.String command3
    );

    @WebMethod(operationName = "DownloadFileCommand", action = "http://tempuri.org/IWebCommonService/DownloadFileCommand")
    @Action(input = "http://tempuri.org/IWebCommonService/DownloadFileCommand", output = "http://tempuri.org/IWebCommonService/DownloadFileCommandResponse")
    @RequestWrapper(localName = "DownloadFileCommand", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.DownloadFileCommand")
    @ResponseWrapper(localName = "DownloadFileCommandResponse", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.DownloadFileCommandResponse")
    @WebResult(name = "DownloadFileCommandResult", targetNamespace = "http://tempuri.org/")
    public byte[] downloadFileCommand(
        @WebParam(name = "commandId", targetNamespace = "http://tempuri.org/")
        java.lang.String commandId,
        @WebParam(name = "command1", targetNamespace = "http://tempuri.org/")
        java.lang.String command1
    );

    @WebMethod(operationName = "SendSpecialCommand3", action = "http://tempuri.org/IWebCommonService/SendSpecialCommand3")
    @Action(input = "http://tempuri.org/IWebCommonService/SendSpecialCommand3", output = "http://tempuri.org/IWebCommonService/SendSpecialCommand3Response")
    @RequestWrapper(localName = "SendSpecialCommand3", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.SendSpecialCommand3")
    @ResponseWrapper(localName = "SendSpecialCommand3Response", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.SendSpecialCommand3Response")
    @WebResult(name = "SendSpecialCommand3Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSpecialCommand3(
        @WebParam(name = "commandId", targetNamespace = "http://tempuri.org/")
        java.lang.String commandId,
        @WebParam(name = "command1", targetNamespace = "http://tempuri.org/")
        java.lang.String command1,
        @WebParam(name = "command2", targetNamespace = "http://tempuri.org/")
        java.lang.String command2,
        @WebParam(name = "command3", targetNamespace = "http://tempuri.org/")
        java.lang.String command3
    );

    @WebMethod(operationName = "SendSpecialCommand2", action = "http://tempuri.org/IWebCommonService/SendSpecialCommand2")
    @Action(input = "http://tempuri.org/IWebCommonService/SendSpecialCommand2", output = "http://tempuri.org/IWebCommonService/SendSpecialCommand2Response")
    @RequestWrapper(localName = "SendSpecialCommand2", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.SendSpecialCommand2")
    @ResponseWrapper(localName = "SendSpecialCommand2Response", targetNamespace = "http://tempuri.org/", className = "com.uds.tc.common.webservice.SendSpecialCommand2Response")
    @WebResult(name = "SendSpecialCommand2Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSpecialCommand2(
        @WebParam(name = "commandId", targetNamespace = "http://tempuri.org/")
        java.lang.String commandId,
        @WebParam(name = "command1", targetNamespace = "http://tempuri.org/")
        java.lang.String command1,
        @WebParam(name = "command2", targetNamespace = "http://tempuri.org/")
        java.lang.String command2
    );
}
