package com.uds.tc.common.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.8
 * 2016-05-06T14:08:22.571+08:00
 * Generated source version: 3.0.8
 * 
 */
@WebServiceClient(name = "WebCommonService", 
                  wsdlLocation = "http://127.0.0.1:8723/WebCommonService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class WebCommonService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "WebCommonService");
    public final static QName BasicHttpBindingIWebCommonService = new QName("http://tempuri.org/", "BasicHttpBinding_IWebCommonService");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8723/WebCommonService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebCommonService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8723/WebCommonService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebCommonService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebCommonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebCommonService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebCommonService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebCommonService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebCommonService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IWebCommonService
     */
    @WebEndpoint(name = "BasicHttpBinding_IWebCommonService")
    public IWebCommonService getBasicHttpBindingIWebCommonService() {
        return super.getPort(BasicHttpBindingIWebCommonService, IWebCommonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebCommonService
     */
    @WebEndpoint(name = "BasicHttpBinding_IWebCommonService")
    public IWebCommonService getBasicHttpBindingIWebCommonService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIWebCommonService, IWebCommonService.class, features);
    }

}
